config/routes.rb
Starbucks::Application.routes.draw do
  root "static_pages#home"
  get "contact" => "static_pages#contact", as: :contact
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :drinks
  resources :materials
  resources :users

end

app/models/drink.rb
class Drink < ActiveRecord::Base
  belongs_to :user
  has_many :drink_materials
  has_many :materials, :through => :drink_materials

end

app/models/drink_material.rb
class DrinkMaterial < ActiveRecord::Base
  belongs_to :drink
  belongs_to :material
end

app/models/material.rb
class Material < ActiveRecord::Base
  belongs_to :mtype
  has_many :drink_materials
  has_many :drinks, :through => :drink_materials
end

app/models/mtype.rb
class Mtype < ActiveRecord::Base
  has_many :materials
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :drinks
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  def self.find_for_facebook_oauth(auth)
	where(auth.slice(:provider, :uid)).first_or_create do |user|
	  user.provider = auth.provider
	  user.uid = auth.uid
	  user.email = auth.info.email
	  user.password = Devise.friendly_token[0,20]
	  user.name = auth.info.name   # assuming the user model has a name
	end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?


  def login_required
    if current_user.blank?
      respond_to do |format|
        format.html  {
          authenticate_user!
        }
        format.js{
          render :partial => "common/not_logined"
        }
        format.all {
          head(:unauthorized)
        }
      end
    end
  
  end

protected
  def configure_permitted_parameters
  	devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password,:password_confirmation)}
  end
end

app/controllers/drinks_controller.rb
class DrinksController < ApplicationController
  before_action :login_required, :only => [:new, :create, :edit, :update, :destroy]
  def index
    @drinks = Drink.all
  end

  def show
    @drink = Drink.find(params[:id])
    @materials = @drink.materials.all
  end

  def edit
    @drink = current_user.drinks.find(params[:id])
    @base = Mtype.find(1).materials
    @syrup = Mtype.find(2).materials
    @additive = Mtype.find(3).materials
  end

  def update
    @drink = current_user.drinks.find(params[:id])
    if @drink.update(drink_params)
      redirect_to drink_path(@drink)
    else
      render :edit
    end
  end

  def new
    @drink = Drink.new
    @base = Mtype.find(1).materials
    @syrup = Mtype.find(2).materials
    @additive = Mtype.find(3).materials
  end

  def create
    @drink = current_user.drinks.build(drink_params)
    if @drink.save

      redirect_to drinks_path
    else
      render :new
    end
  end

  def destroy
    @drink = current_user.drinks.find(params[:id])
    @drink.destroy
    redirect_to user_path(current_user)
  end



private

  def drink_params
    params.require(:drink).permit(:name, :way, :description, :user_id, material_ids:[])    
  end

end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
  def new
  	@material = Material.new
    @mtype = Mtype.all
  end

  def create
  	@material = Material.new(material_params)
  	if @material.save
  		redirect_to material_path(@material)
  	else
  		render :new
  	end
  end

  def index
  	@materials = Material.all
  end

  def edit
  	@material = Material.find(params[:id])
  end

  def update
  	
  end

  def show
  	@material = Material.find(params[:id])
  end

private

  def material_params
  	params.require(:material).permit(:name, :mtype_id, :available)
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def contact
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"])
    puts "heloooooo!!!!!!world!!!"
    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"].except('extra')
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @drinks = @user.drinks.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/drinks_helper.rb
module DrinksHelper
  def list_materials(type)
    type.collect { |m| concat(content_tag(:li, m.name, :id => m.id, :class => "list-group-item pointer", :type => m.mtype.name,:status => "false")) }
  end
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def user_auth(user)
    (current_user && user == current_user)? true : false
  end
end

app/views/common/_drinks_list.html.erb
    
    <div class="panel panel-default">
      <div class="panel-heading">Drinks</div>
      <table class="table">
        <thead>
          <td>#</td>
          <td>Name</td>
          <td>Description</td>
        </thead>
        <% @drinks.each do |drink| %>
          <tr>
            <td><%= drink.id %></td>
            <td><%= link_to( truncate(drink.name, :length => 30), drink_path(drink)) %></td>
            <td><%= truncate(drink.description, :length => 50) %></td>
            <td>
              <% if current_user && drink.user == current_user %>
                <%= link_to("Edit", edit_drink_path(drink)) %>
                <%= link_to("Delete", drink_path(drink), :method => :delete, :confirm => "Are you sure?")%>
              <% end %>
            </td>
          </tr></a>
        <% end %>
      </table>

    </div>

app/views/common/_fb_share.html.erb
  <%= link_to("跟Facebook朋友分享", "https://www.facebook.com/sharer/sharer.php?u=#{request.original_url}", :class => "btn btn-lg btn-primary", :target => "_blank") %>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <%= link_to("Starbucks Drink Mixer", root_path, :class => "navbar-brand") %>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to("飲料列表", drinks_path) %></li>
        <li><%= link_to("其他使用者的飲料", users_path) %></li>

        <% if current_user %>
          <!-- user logined information -->
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.name %><b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to("My Drinks",user_path(current_user)) %></li>
              <li class="divider"></li>
              <li><%= link_to("Logout",destroy_user_session_path,:method=>:delete) %></li>
            </ul>
          </li>
        <% else %>
          <!-- user not_logined information -->
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Join Us and Have Fun<b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "使用Facebook登入（建議）", user_omniauth_authorize_path(:facebook) %></li>
              <li class="divider"></li>
              <li><%= link_to("註冊",new_user_registration_path) %></li>
              <li><%= link_to("登入",new_user_session_path) %></li>
              
            </ul>
          </li>
          
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/common/_not_logined.js.erb
if (confirm("Please login first, proceed?") )
{
  window.location = "/users/sign_in";
}

app/views/drinks/_disqus.html.erb
    <div id="disqus_thread"></div>
    <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'sdm-v1'; // required: replace example with your forum shortname
        
        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
    <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
    

app/views/drinks/_disqus_count.html.erb
    <script type="text/javascript">
    /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
    var disqus_shortname = 'sdm-v1'; // required: replace example with your forum shortname
    
    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function () {
        var s = document.createElement('script'); s.async = true;
        s.type = 'text/javascript';
        s.src = '//' + disqus_shortname + '.disqus.com/count.js';
        (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
    }());
    </script>

app/views/drinks/_facebook_share.html.erb
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/zh_TW/all.js#xfbml=1&appId=1411102179161226";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

app/views/drinks/_facebook_share_setup.html.erb
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/zh_TW/all.js#xfbml=1&appId=1411102179161226";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

app/views/drinks/edit.html.erb
<h1>飲料調配大師</h1>

<div id="select-materials" class="row">
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">飲料底液</div>
      <ul id="base" class="list-group">
          <% list_materials(@base) %>
      </ul>
    </div>
  </div>
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">糖漿</div>
      <ul id="syrup" class="list-group">
        <% list_materials(@syrup) %>
      </ul>
    </div>
  </div>
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">添加物</div>
      <ul id="additive" class="list-group">
        <% list_materials(@additive) %>
      </ul>
    </div>
  </div>
</div><!-- end of .row -->
<div id="selected-materials" class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="panel panel-success">
      <div class="panel-heading">選擇的內容</div>
      <ul class="list-group"></ul>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%=  simple_form_for @drink do |f| %>
      <%= f.input :name, :input_html => { :class => "input-xxlarge form-control"} %>
      <%= f.input :way, :input_html => { :class => "input-xxlarge form-control"} %>
      <%= f.input :description, :input_html => { :class => "input-xxlarge form-control"} %>
      <%= f.association :materials, :as => :check_boxes %>
      <br>
      <div class="form-actions">
        <%= f.submit "Submit", :disable_with => 'Submiting...', :class => "btn btn-success form-control"%>
      </div>
    <% end %>
  </div>
</div>

<script type="text/javascript">
  $(document).ready(function(){
    var checked_list = [];
    var $check_boxes = $(".check_boxes");
    console.log($check_boxes);
    $check_boxes.each(function(i, check_box){
      if (check_box.checked) {
        checked_list.push(check_box.value);
      };
    });
    $.each(checked_list, function(i, value){
      obj = "#" + value
      $(obj).appendTo("#selected-materials ul");
      $(obj).attr("status", true);
    });
  });

</script>

app/views/drinks/index.html.erb
<div class="row centered">
  <div class="col-md-8 col-md-offset-2">
    <h1>Drink Lists</h1>
    <%= render :partial => "common/drinks_list" %>


  </div>
</div>

app/views/drinks/new.html.erb
<h1>飲料調配大師</h1>

<div id="select-materials" class="row">
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">飲料底液</div>
      <ul id="base" class="list-group">
          <% list_materials(@base) %>
      </ul>
    </div>
  </div>
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">糖漿</div>
      <ul id="syrup" class="list-group">
        <% list_materials(@syrup) %>
      </ul>
    </div>
  </div>
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">添加物</div>
      <ul id="additive" class="list-group">
        <% list_materials(@additive) %>
      </ul>
    </div>
  </div>
</div><!-- end of .row -->
<div id="selected-materials" class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="panel panel-success">
      <div class="panel-heading">選擇的內容</div>
      <ul class="list-group"></ul>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%=  simple_form_for @drink do |f| %>
      <%= f.input :name, :input_html => { :class => "input-xxlarge form-control"} %>
      <%= f.input :way, :input_html => { :class => "input-xxlarge form-control"} %>
      <%= f.input :description, :input_html => { :class => "input-xxlarge form-control"} %>
      <%= f.association :materials, :as => :check_boxes %>
      <br>
      <div class="form-actions">
        <%= f.submit "Submit", :disable_with => 'Submiting...', :class => "btn btn-success form-control"%>
      </div>
    <% end %>
  </div>
</div>

app/views/drinks/show.html.erb
<%= render :partial => "facebook_share_setup" %>
<div class="row centered">
  <div class="col-md-12">
    <h1><%= @drink.name %></h1>
  </div>
</div>


<div class="row">
  <!-- materials-info & drink-way-info -->
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">飲料原料</div>
      <ul id="base" class="list-group">
        <% @materials.each do |m| %>
          <li class="list-group-item <%= m.mtype.name %>"><%= m.name %></li>
        <% end %>
      </ul>
    </div>

    <!-- drink-way-info -->
    <div class="panel panel-default">
      <div class="panel-heading">製作方式</div>
      <div class="panel-body">
        <%= simple_format(@drink.way) %>
      </div>
    </div>

  </div>

  <!-- drink-description-info -->
  <div class="col-md-8">
    <div class="panel panel-warning">
      <div class="panel-heading">飲料特色</div>
      <div class="panel-body">
        <%= simple_format(@drink.description) %>
      </div>
    </div>
  </div>
</div><!-- end of row -->
<div class="row centered">
  <div class="col-md-12">
    <p>Drink Made By <%= link_to(@drink.user.name, user_path(@drink.user)) %></p>
  </div>
</div>





<div class="row centered">
  <%= render :partial => "common/fb_share" %>
</div>



<%= render :partial => "disqus" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Starbucks</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render :partial => "common/navbar" %>

  <div class="container">
    <% flash.each do |key, value| %>
          <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
    <%= yield %>
  </div>

  <div id="footer">
    <div class="container">
      <hr>
      <div class="pull-right">
        <%= link_to("Contact Us", "/contact", :class => "text-muted") %>
      </div>
    </div>
  </div>

</body>
</html>

app/views/materials/edit.html.erb
<h1>Materials#edit</h1>
<p>Find me in app/views/materials/edit.html.erb</p>

app/views/materials/index.html.erb
<h1>Materials#index</h1>
<p>Find me in app/views/materials/index.html.erb</p>

app/views/materials/new.html.erb
<%=  simple_form_for @material do |f| %>
  <%= f.input :name, :input_html => { :class => "input-xxlarge"} %>
  <%= f.input :mtype_id, :collection => @mtype, :label_method => :name, :value_method => :id,:label => "Material Type", :input_html => { :class => "input-xxlarge"} %>
  <div class="form-actions">
    <%= f.submit "Submit", :disable_with => 'Submiting...', :class => "btn btn-primary"%>
  </div>
<% end %>

app/views/materials/show.html.erb
<h1>Materials#show</h1>
<p>Find me in app/views/materials/show.html.erb</p>

app/views/static_pages/contact.html.erb
<div class="jumbotron bg-white">
<h1>Hi there</h1>
<p>Starbucks Drink Mixer is a little project that make people find their special and favorite drink in starbucks.  It's nothing to do with Starbucks corp., just have fun and enjoy it. :)  </p>
<p>If you have any suggestions or just want to talk, you can contact us by google doc here: <%= link_to("Google Doc", "http://goo.gl/gDBsI2", :target => "_blank") %>, we will reply you ASAP.</p>
<p>Thanks for your attention. Wish you have a good time here.</p>
<p>-SDM team</p>
</div>

app/views/static_pages/home.html.erb
<div class="jumbotron centered">
  <h1>Starbucks Drink Mixer</h1>
  <h2>--Make your special Starbucks Drink</h2>
  <p>你知道Starbucks的隱藏MENU嗎？</p>
  <p>你知道Starbucks有超過3000種飲料組合嗎？</p>
  <p>別再傻傻不知道喝什麼了</p>
  <p>加入我們，一起發掘最特殊的喝法吧</p>
  <h3>現在就建立屬於你的星巴克飲品</h3>
  <p><%= link_to("Make Your Drink Now", new_drink_path, :class => "btn  btn-lg btn-success") %></p>
  <p>~~Or~~</p>
  <h3>參考其他使用者推薦的飲料</h3>
  <p><%= link_to("Discover Other's Drinks", drinks_path, :class => "btn  btn-lg btn-warning") %></p>
</div>

app/views/users/index.html.erb
<h1>Users</h1>
<% @users.each do |user| %>
  <p><%= link_to(user.name, user_path(user)) %></p>
<% end %>

app/views/users/show.html.erb
<%= render :partial => "drinks/facebook_share_setup" %>
<div class="row centered">
  <div class="col-md-8 col-md-offset-2">
    <h1><%= @user.name %></h1>
    <%= render :partial => "common/drinks_list" %>
  </div>
    <%= link_to("+新增飲料", new_drink_path(current_user)) if user_auth(@user)%>
</div>

<div class="row centered">
  <%= render :partial => "common/fb_share" %>
</div>